<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="aniket-Latitude-3410" failures="1" tests="2" name="dashboardBucketsPack.MissedSitevisit_VerificationTest" time="103.763" errors="0" timestamp="2023-07-11T18:35:25 IST" skipped="1">
  <testcase classname="dashboardBucketsPack.MissedSitevisit_VerificationTest" name="missedSitevisit_VerificationTest" time="48.321">
    <failure message="Count is same as before scheduling site visit did not expect [39] but found [39]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Count is same as before scheduling site visit did not expect [39] but found [39]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failEquals(Assert.java:1581)
at org.testng.Assert.assertNotEqualsImpl(Assert.java:156)
at org.testng.Assert.assertNotEquals(Assert.java:2197)
at dashboardBucketsPack.MissedSitevisit_VerificationTest.missedSitevisit_VerificationTest(MissedSitevisit_VerificationTest.java:60)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:263)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- missedSitevisit_VerificationTest -->
  <system-out/>
  <testcase classname="dashboardBucketsPack.MissedSitevisit_VerificationTest" name="missedSitevisit_VerificationTest" time="55.442">
    <skipped/>
  </testcase> <!-- missedSitevisit_VerificationTest -->
  <system-out/>
</testsuite> <!-- dashboardBucketsPack.MissedSitevisit_VerificationTest -->
